import type { Metadata } from "next";
import "./globals.css";
import Luciole from '@/fonts/luciole';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[Luciole.className, "bg-slate-100"].join(' ')}>
        <Header />
        <section className="container p-4">
          {children}
        </section>
      </body>
    </html>
  );
}
